name: Clean cache

on:
  pull_request:
    types:
    - closed
  workflow_dispatch:
    inputs:
      PR_NUMBER:
        description: ID number of the pull request associated with the cache
        required: false
        type: number
      BRANCH_NAME:
        description: Branch name associated with the cache
        required: false
        type: string

jobs:
  clean-cache:
    uses: this-is-tobi/github-workflows/.github/workflows/clean-cache.yml@v0
    permissions:
      actions: write
      packages: write
    with:
      PR_NUMBER: ${{ github.event.pull_request.number || inputs.PR_NUMBER || 0 }}
      BRANCH_NAME: ${{ inputs.BRANCH_NAME || '' }}
      IMAGE: ${{ format('ghcr.io/{0}/docpress:{1}', github.repository_owner, inputs.BRANCH_NAME || format('pr-{0}', github.event.pull_request.number || inputs.PR_NUMBER || '0')) }}
      CLEAN_GH_CACHE: true
      CLEAN_GHCR_IMAGE: true
