name: CD

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  BUN_VERSION: latest

jobs:
  expose-vars:
    runs-on: ubuntu-latest
    outputs:
      BUN_VERSION: ${{ env.BUN_VERSION }}
    steps:
    - name: Exposing env vars
      run: echo "Exposing env vars"

  release:
    uses: this-is-tobi/github-workflows/.github/workflows/release-app.yml@v0
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      TAG_MAJOR_AND_MINOR: true

  npm:
    uses: this-is-tobi/github-workflows/.github/workflows/release-npm.yml@v0
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs:
    - expose-vars
    - release
    permissions:
      contents: read
      id-token: write
    with:
      RUNTIME: bun
      RUNTIME_VERSION: ${{ needs.expose-vars.outputs.BUN_VERSION }}
      PACKAGE_MANAGER: bun
      BUILD_COMMAND: bun run build
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  docker:
    uses: this-is-tobi/github-workflows/.github/workflows/build-docker.yml@v0
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs:
    - release
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/docpress
      IMAGE_TAG: ${{ needs.release.outputs.version }}
      IMAGE_DOCKERFILE: ./Dockerfile
      IMAGE_CONTEXT: ./
      IMAGE_TARGET: prod
      TAG_MAJOR_AND_MINOR: true
      LATEST_TAG: true
