name: Tests - docker

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      DOCKER_IMAGE:
        description: Docker image used for tests
        required: false
        type: string

jobs:
  docker-tests:
    name: Docker tests
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v6

    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Run docker tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}
      run: ./ci/scripts/run-tests.sh -d "$DOCKER_IMAGE"
