name: Tests - docker

on:
  workflow_call:
    inputs:
      PNPM_VERSION:
        required: true
        type: string
      DOCKER_IMAGE:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      PNPM_VERSION:
        description: Pnpm version used to run tests
        required: true
        type: string
        default: 9.12.3
      DOCKER_IMAGE:
        description: Docker image used for tests
        required: false
        type: string

jobs:
  docker-tests:
    name: Docker tests
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      id: pnpm-install
      with:
        version: "${{ inputs.PNPM_VERSION }}"
        run_install: false

    - name: Run docker tests
      run: ./ci/scripts/run-tests.sh -d ${{ inputs.DOCKER_IMAGE }}
