name: Tests - docker

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      DOCKER_IMAGE:
        description: Docker image used for tests
        required: false
        type: string

jobs:
  docker-tests:
    name: Docker tests
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v6

    - name: Setup Corepack
      run: |
        npm install -g corepack@latest
        corepack enable

    - name: Run docker tests
      run: ./ci/scripts/run-tests.sh -d ${{ inputs.DOCKER_IMAGE }}
